# Generated by Django 4.2.6 on 2024-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
