# Generated by Django 4.2.6 on 2024-02-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("place", "0002_alter_place_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="day",
        ),
        migrations.AddField(
            model_name="place",
            name="parent_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="parent_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
