# Generated by Django 5.0.2 on 2024-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_alter_agenda_options_agenda_is_itinerary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="status",
        ),
        migrations.AddField(
            model_name="place",
            name="record_type",
            field=models.CharField(
                choices=[("PL", "PLACE"), ("NO", "Note"), ("CH", "Checklist")],
                default="PL",
                max_length=2,
            ),
        ),
    ]
