# Generated by Django 4.2.6 on 2023-10-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("day", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="sequence_number",
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
