# Generated by Django 4.2.6 on 2023-10-24 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("day", "0002_day_sequence_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="sequence_number",
            new_name="order",
        ),
    ]
