# Generated by Django 4.2.6 on 2024-01-29 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attraction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="reservation_cost",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
