# Generated by Django 4.2.6 on 2024-01-28 23:02

import common.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("day", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "checked_status",
                    enumchoicefield.fields.EnumChoiceField(
                        default=common.enums.CHECKED_STATUS["UNSELECTED"],
                        enum_class=common.enums.CHECKED_STATUS,
                        max_length=10,
                    ),
                ),
                (
                    "reservation_place_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "reservation_link",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "reservation_file",
                    models.FileField(blank=True, null=True, upload_to="reservations/"),
                ),
                ("reservation_date", models.DateField(blank=True, null=True)),
                ("reservation_time", models.TimeField(blank=True, null=True)),
                (
                    "reservation_status",
                    enumchoicefield.fields.EnumChoiceField(
                        default=common.enums.RESERVATION_STATUS["NO"],
                        enum_class=common.enums.RESERVATION_STATUS,
                        max_length=6,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "category",
                    enumchoicefield.fields.EnumChoiceField(
                        default=common.enums.Category["EXPERIENCE"],
                        enum_class=common.enums.Category,
                        max_length=10,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attractions",
                        to="day.day",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
