suggestion_4 = [
    {
        "day_number": "1st day",
        "time": "09:00",
        "name": "Taj Mahal",
        "city": "Agra",
        "category": "historic site",
    },
    {
        "day_number": "1st day",
        "time": "14:00",
        "name": "Jama Masjid",
        "city": "Delhi",
        "category": "historic site",
    },
    {
        "day_number": "2nd day",
        "time": "10:00",
        "name": "Amber Palace",
        "city": "Jaipur",
        "category": "historic site",
    },
    {
        "day_number": "2nd day",
        "time": "15:00",
        "name": "Hawa Mahal",
        "city": "Jaipur",
        "category": "historic site",
    },
    {
        "day_number": "3rd day",
        "time": "09:30",
        "name": "Varanasi Ghats",
        "city": "Varanasi",
        "category": "cultural activity",
    },
    {
        "day_number": "3rd day",
        "time": "14:00",
        "name": "Sarnath",
        "city": "Varanasi",
        "category": "historic site",
    },
    {
        "day_number": "4th day",
        "time": "10:00",
        "name": "Mehrangarh Fort",
        "city": "Jodhpur",
        "category": "historic site",
    },
    {
        "day_number": "4th day",
        "time": "15:00",
        "name": "Mandore Gardens",
        "city": "Jodhpur",
        "category": "historic site",
    },
    {
        "day_number": "5th day",
        "time": "09:00",
        "name": "Ranthambore National Park",
        "city": "Sawai Madhopur",
        "category": "adventurous place",
    },
    {
        "day_number": "5th day",
        "time": "14:00",
        "name": "Ranthambore Fort",
        "city": "Sawai Madhopur",
        "category": "historic site",
    },
    {
        "day_number": "6th day",
        "time": "10:00",
        "name": "Ellora Caves",
        "city": "Aurangabad",
        "category": "historic site",
    },
    {
        "day_number": "6th day",
        "time": "15:00",
        "name": "Bibi Ka Maqbara",
        "city": "Aurangabad",
        "category": "historic site",
    },
    {
        "day_number": "7th day",
        "time": "09:30",
        "name": "Kerala Backwaters",
        "city": "Alappuzha",
        "category": "cultural activity",
    },
    {
        "day_number": "7th day",
        "time": "14:00",
        "name": "Kochi Fort",
        "city": "Kochi",
        "category": "historic site",
    },
    {
        "day_number": "8th day",
        "time": "10:00",
        "name": "Meenakshi Amman Temple",
        "city": "Madurai",
        "category": "historic site",
    },
    {
        "day_number": "8th day",
        "time": "15:00",
        "name": "Gandhi Memorial Museum",
        "city": "Madurai",
        "category": "historic site",
    },
    {
        "day_number": "9th day",
        "time": "09:00",
        "name": "Mysore Palace",
        "city": "Mysore",
        "category": "historic site",
    },
    {
        "day_number": "9th day",
        "time": "14:00",
        "name": "Brindavan Gardens",
        "city": "Mysore",
        "category": "cultural activity",
    },
    {
        "day_number": "10th day",
        "time": "10:00",
        "name": "Gateway of India",
        "city": "Mumbai",
        "category": "historic site",
    },
    {
        "day_number": "10th day",
        "time": "15:00",
        "name": "Elephanta Caves",
        "city": "Mumbai",
        "category": "historic site",
    },
]

suggestion_3 = [
    {
        "day_number": "1st day",
        "time": "3 hours",
        "name": "La Alcazaba",
        "city": "Málaga",
        "category": "historic site",
    },
    {
        "day_number": "2nd day",
        "time": "2 hours",
        "name": "Museo Picasso Málaga",
        "city": "Málaga",
        "category": "cultural activity",
    },
    {
        "day_number": "3rd day",
        "time": "4 hours",
        "name": "Caminito del Rey",
        "city": "Álora",
        "category": "adventurous place",
    },
    {
        "day_number": "4th day",
        "time": "5 hours",
        "name": "Parque Natural Montes de Málaga",
        "city": "Málaga",
        "category": "adventurous place",
    },
    {
        "day_number": "5th day",
        "time": "2 hours",
        "name": "Catedral de Málaga",
        "city": "Málaga",
        "category": "historic site",
    },
]
suggestion_2 = [
    {
        "day_number": "1st day",
        "time": "4 hours",
        "name": "Santiago Bernabeu Stadium",
        "city": "Madrid",
        "category": "Adventurous",
    },
    {
        "day_number": "2nd day",
        "time": "6 hours",
        "name": "Alhambra",
        "city": "Granada",
        "category": "Historic",
    },
    {
        "day_number": "3rd day",
        "time": "3 hours",
        "name": "Passeig de Gracia",
        "city": "Barcelona",
        "category": "Cultural",
    },
    {
        "day_number": "4th day",
        "time": "2 hours",
        "name": "Guggenheim Museum",
        "city": "Bilbao",
        "category": "Historic",
    },
    {
        "day_number": "5th day",
        "time": "4 hours",
        "name": "La Tomatina Festival",
        "city": "Buñol",
        "category": "Adventurous",
    },
]

suggestion_1 = [
    {
        "category": "Adventure",
        "day_number": "1st day",
        "city": "Paro",
        "name": "Tiger's Nest",
        "time": "9am",
    },
    {
        "category": "Historic",
        "day_number": "1st day",
        "city": "Agra",
        "name": "Taj Mahal",
        "time": "3pm",
    },
    {
        "category": "Adventure",
        "day_number": "2nd day",
        "city": "Goa",
        "name": "Dudhsagar Falls",
        "time": "9am",
    },
    {
        "category": "Historic",
        "day_number": "2nd day",
        "city": "Jodhpur",
        "name": "Mehrangarh Fort",
        "time": "3pm",
    },
    {
        "category": "Cultural",
        "day_number": "2nd day",
        "city": "Kochi",
        "name": "Kathakali Performance",
        "time": "6pm",
    },
]
