# Generated by Django 5.0.2 on 2024-03-12 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ("agenda__itinerary",)},
        ),
    ]
