# Generated by Django 5.0.2 on 2024-03-12 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0002_alter_place_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ("order",)},
        ),
    ]
