# Generated by Django 5.0.2 on 2024-02-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0002_alter_itinerary_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="Itinerary",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="itinerary.itinerary",
            ),
            preserve_default=False,
        ),
    ]
