# Generated by Django 5.0.2 on 2024-02-13 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0003_day_itinerary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="Itinerary",
            new_name="itinerary",
        ),
    ]
