# Generated by Django 5.0.2 on 2024-03-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0003_alter_place_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="time",
            new_name="end_time",
        ),
        migrations.RemoveField(
            model_name="place",
            name="date",
        ),
        migrations.AddField(
            model_name="place",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
