# Generated by Django 5.0.2 on 2024-02-15 17:52

import common.enums
import django.core.validators
import enumchoicefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "itinerary",
            "0007_day_created_at_day_updated_at_itinerary_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="places",
            name="cost",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="places",
            name="currency",
            field=models.CharField(blank=True, default="EUR", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="places",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="places",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="reservations/"),
        ),
        migrations.AddField(
            model_name="places",
            name="link",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="places",
            name="status",
            field=enumchoicefield.fields.EnumChoiceField(
                default=common.enums.RESERVATION_STATUS["NO"],
                enum_class=common.enums.RESERVATION_STATUS,
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="places",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
