# Generated by Django 5.0.2 on 2024-02-22 19:19

import common.enums
import django.core.validators
import django.db.models.deletion
import enumchoicefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "itinerary",
            "0008_itinerary_end_date_itinerary_start_date_places_cost_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("link", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="reservations/"),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    enumchoicefield.fields.EnumChoiceField(
                        default=common.enums.RESERVATION_STATUS["UNSET"],
                        enum_class=common.enums.RESERVATION_STATUS,
                        max_length=6,
                    ),
                ),
                (
                    "cost",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="EUR", max_length=3, null=True
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.DeleteModel(
            name="Places",
        ),
    ]
