# Generated by Django 5.0.2 on 2024-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0009_place_delete_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="text",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
