# Generated by Django 5.0.2 on 2024-02-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0012_alter_day_title_alter_place_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
