# Generated by Django 5.0.2 on 2024-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0013_alter_place_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="cost",
        ),
        migrations.AddField(
            model_name="place",
            name="decimal_field",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
