# Generated by Django 5.0.2 on 2024-02-27 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0014_remove_place_cost_place_decimal_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="decimal_field",
            new_name="cost",
        ),
    ]
