# Generated by Django 4.2.6 on 2024-02-12 17:16

import common.enums
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("place_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "reservation_link",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "reservation_file",
                    models.FileField(blank=True, null=True, upload_to="reservations/"),
                ),
                ("reservation_date", models.DateField(blank=True, null=True)),
                ("reservation_time", models.TimeField(blank=True, null=True)),
                (
                    "reservation_status",
                    enumchoicefield.fields.EnumChoiceField(
                        default=common.enums.RESERVATION_STATUS["NO"],
                        enum_class=common.enums.RESERVATION_STATUS,
                        max_length=6,
                    ),
                ),
                (
                    "reservation_cost",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
