# Generated by Django 4.2.6 on 2023-10-24 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("order",)},
        ),
    ]
