# Generated by Django 4.2.6 on 2023-10-22 02:05

import common.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import experience.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("itinerary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "reservation_place_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "reservation_link",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "reservation_file",
                    models.FileField(blank=True, null=True, upload_to="reservations/"),
                ),
                ("reservation_date", models.DateField(blank=True, null=True)),
                ("reservation_time", models.TimeField(blank=True, null=True)),
                (
                    "reservation_status",
                    enumchoicefield.fields.EnumChoiceField(
                        default=common.enums.RESERVATION_STATUS["NO"],
                        enum_class=common.enums.RESERVATION_STATUS,
                        max_length=6,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=180)),
                (
                    "type",
                    enumchoicefield.fields.EnumChoiceField(
                        default=experience.models.ExperienceTypes(4),
                        enum_class=experience.models.ExperienceTypes,
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="itinerary.itinerary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "itinerary")},
            },
        ),
    ]
