# Generated by Django 4.2.6 on 2023-10-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0001_initial"),
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="itinerary",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="itinerary.itinerary",
            ),
            preserve_default=False,
        ),
    ]
