# Generated by Django 4.2.6 on 2023-10-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attraction",
            options={"ordering": ("order",)},
        ),
        migrations.AlterField(
            model_name="attraction",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
